### PR TITLE
fix constructor params

### LINKED ISSUE #71: Change the constructors structure
- [x] allow the constructor to take in objects in form of interfaces
- [x] add optional parameters
For instance
Battery
`constructor(x:number, y:number)` could be written as
`constructor(batteryParams)` where 
``` 
interface batteryParams {
   x: number,
   y: number,
}
```

### PR DESCRIPTION
**Pull request by RolandNaijuka**
- fix the constructor params
- use interfaces in cases where there multiple parameters
- make gridItemName compulsory for all gridItems i.e battery, building, solar panel. This ensures that all buildings show up on the grid since they have different name
- fixes the changes suggested by @cwlarson-google 

Fixes #71

### CODE REVIEW

File: biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts [hunk 1]
```diff
@@ -24,25 +33,18 @@ export class BioBattery implements Battery {
...
-        `Cannot create a battery with values: (${energyInJoules}, ${maxCapacity})`
+        `Cannot create a battery with values: (${batteryParams.energyInJoules}, ${batteryParams.maxCapacity})`
       );
     }
-    this.energyInJoules = energyInJoules;
-    this.maxCapacity = maxCapacity;
-    this.gridItemName = gridItemName;
-    this.gridItemResistance = gridItemResistance;
+    this.energyInJoules = batteryParams.energyInJoules;
+    this.maxCapacity = batteryParams.maxCapacity ? batteryParams.maxCapacity : SMALL_BATTERY.MAX_CAPACITY;
```
Comment (cwlarson-google) [inline biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts]: I believe you can consolidate this to
`this.maxCapacity = batteryParams.maxCapacity || SMALL_BATTERY.MAX_CAPACITY;`

File: biogrid/libs/biogrid-simulator/src/lib/biobrain/biobrain.spec.ts [hunk 2]
```diff
@@ -13,9 +13,24 @@ const name3 = `${GRID_ITEM_NAMES.ENERGY_USER}-3`;
...
   actualBrain = BioBrain.Instance;
   const ruralArea = [
-    new Building(BUILDING.MAX_CAPACITY, 3, 4, name1),
-    new Building(0, 7, 9, name2),
-    new Building(BUILDING.MAX_CAPACITY, 7, 8, name3),
+    new Building({
+      energy: BUILDING.MAX_CAPACITY,
+      x: 3,
+      y: 4,
+      gridItemName: name1
```
Comment (cwlarson-google) [inline biogrid/libs/biogrid-simulator/src/lib/biobrain/biobrain.spec.ts]: I know it's not part of this PR, but these constants should be uppercase `const MY_GLOBAL_CONSTANT = 'abc';`

File: biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts (hunk 1 above)
Comment (cwlarson-google) [reply biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts]: To be more consistent with how you handle optional params later in this PR, maybe best to do
```
export class BioBattery implements Battery {
  private readonly maxCapacity: Energy = SMALL_BATTERY.MAX_CAPACITY;
  ...
  constructor(...) {
    ...
    if (batteryParams.maxCapacity) {
      this.maxCapacity = batteryParams.maxCapacity;
    }
  }
}
```

File: biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts [hunk 3]
```diff
@@ -1,45 +1,40 @@
...
   Power,
-  SunlightIntensity,
-  Distance,
   CloudCoverage,
 } from '@biogrid/grid-simulator';
-import { SOLAR_PANEL, GRID_ITEM_NAMES, RESISTANCE } from '../config';
+import { SOLAR_PANEL, RESISTANCE } from '../config';
+
+export interface SolarPanelParams extends EnergySourceParams {
+  sizeSqMtr: number,
```
Comment (cwlarson-google) [inline biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts]: Nit: `areaSquareMeters`?

File: biogrid/libs/biogrid-simulator/src/lib/building/building.ts [hunk 4]
```diff
@@ -1,11 +1,19 @@
...
-import { GRID_ITEM_NAMES, BUILDING, RESISTANCE } from '../config';
+import { BUILDING, RESISTANCE } from '../config';
+
+export interface BuildingParams {
+  energy: number,
+  x: Distance,
+  y: Distance,
+  gridItemName: string,
+  readonly minCapacity?: Energy,
+  readonly maxCapacity?: Energy,
```
Comment (cwlarson-google) [inline biogrid/libs/biogrid-simulator/src/lib/building/building.ts]: I don't understand the value of setting these as readonly, since this is just an interface for the params, not the Building class itself

File: biogrid/libs/biogrid-simulator/src/lib/building/building.ts [hunk 5]
```diff
@@ -23,21 +31,22 @@ export class Building implements EnergyUser {
...
+  constructor(buildingParams: BuildingParams) {
+    this.relativePosition = { x: buildingParams.x, y: buildingParams.y };
+    this.gridItemName = buildingParams.gridItemName;
+    if (this.isPositive(buildingParams.energy)) {
+      this.energyInJoules = buildingParams.energy;
     } else {
       throw new Error("Can't create a building with negative energy!");
     }
+    this.minCapacity = buildingParams.minCapacity ? buildingParams.minCapacity : BUILDING.MIN_CAPACITY;
+    this.maxCapacity = buildingParams.maxCapacity ? buildingParams.maxCapacity : BUILDING.MAX_CAPACITY;
```
Comment (cwlarson-google) [inline biogrid/libs/biogrid-simulator/src/lib/building/building.ts]: To match the pattern you're using in other files, you can default these using `private readonly minCapacity: Energy = BUILDING.MIN_CAPACITY` above the constructor, and conditionally override the value in the constructor

**Review by cwlarson-google — APPROVED** [review]

File: biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.spec.ts [hunk 6]
```diff
@@ -52,16 +65,16 @@ describe('tests for the BioEnergySource', () => {
       latitude = 0,
       area = 10,
       date = new Date('07/20/2020');
-    const energySource = new SolarPanel(
+    const energySource = new SolarPanel({
       x,
       y,
-      area,
-      GRID_ITEM_NAMES.SOLAR_PANEL,
+      sizeSqMtr: area,
```
Comment (vitashubin) [inline biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.spec.ts]: areaSqMtr as well

**Review by vitashubin — APPROVED** [review]
Approved pending Casey's comments

File: biogrid/libs/biogrid-simulator/src/lib/biobrain/biobrain.spec.ts (hunk 2 above)
Comment (RolandNaijuka) [reply biogrid/libs/biogrid-simulator/src/lib/biobrain/biobrain.spec.ts]: I will address this

File: biogrid/libs/biogrid-simulator/src/lib/building/building.ts (hunk 4 above)
Comment (RolandNaijuka) [reply biogrid/libs/biogrid-simulator/src/lib/building/building.ts:15]: I thought that it would be the same as the one for the building, I will address this

Comment (RolandNaijuka) [reply biogrid/libs/biogrid-simulator/src/lib/building/building.ts]: > I don't understand the value of setting these as readonly, since this is just an interface for the params, not the Building class itself

I thought that it would be the same as the one for the building, I will address this
