### PR TITLE
Roland/fix grid position

### LINKED ISSUE #75: Put Biogrid in middle position
- [x] add the grid in the middle of the town so that it is in the middle of the graph as well

### PR DESCRIPTION
**Pull request by RolandNaijuka**
- put the grid in the middle of the town

Closes #75

### CODE REVIEW

File: biogrid/libs/biogrid-simulator/src/lib/config/bio-constants.ts [hunk 1]
```diff
@@ -136,3 +136,20 @@ export interface ShortestDistances {
 export const TIME = {
   DISCRETE_UNIT_HOURS: 1,
 };
+
+export class MAIN_GRID implements GridItem {
+  gridItemName: string = GRID_ITEM_NAMES.GRID;
+  gridItemResistance: number = RESISTANCE.GRID;
+  //
```
Comment (aosmann7) [inline biogrid/libs/biogrid-simulator/src/lib/config/bio-constants.ts]: delete?

**Review by aosmann7 — APPROVED** [review]
LGTM

File: biogrid/libs/biogrid-simulator/src/lib/config/bio-constants.ts (hunk 1 above)
Comment (RolandNaijuka) [reply biogrid/libs/biogrid-simulator/src/lib/config/bio-constants.ts]: yeah, I removed it. This was in the previous commit
