### PR TITLE
Fix UI and Date

### LINKED ISSUE #86: Fix UI and UX
- [x] Change date selector to a slider for the passed seven days
- [x] Add pause button to simulation
- [x] Charts etc fit on background
- [x] Loading Spinner
- [ ] Space between table and image

### PR DESCRIPTION
**Pull request by Lev-Stambler**
closes #86 
- Change date selector to a slider for the passed seven days
- Add pause button to simulation
- Loading Spinner
- Space between table and image
- Fix date not working bug if not today
- Display efficiency in the frontend

Relies on #85 

[Demo](https://biogrid.herokuapp.com/)

### CODE REVIEW

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx [hunk 1]
```diff
@@ -103,20 +105,21 @@ export const InputPage = () => {
...
-            onChange={(date: Date) => setStartDate(date)}
-          />
-        </div>
-        <div className="endDatePicker">
-          <label>End Date</label>
-          <DatePicker
-            showPopperArrow={false}
-            selected={endDate}
-            onChange={(date: Date) => setEndDate(date)}
+        <div className="datePicker">
```
Comment (cwlarson-google) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Nit: `datePicker` is a known component type, with a calendar and everything.  To avoid confusion, give this class another name like `dateSlider`

**Review by cwlarson-google — APPROVED** [review]

File: biogrid/apps/biogrid-mvp/src/app/components/simulation-board.tsx [hunk 2]
```diff
@@ -127,46 +127,51 @@ export const SimulationBoard = (props: SimBoardProps) => {
...
+                    orient="auto"
+                  >
+                    <polygon points="0 0, 10 3.5, 0 7" />
+                  </marker>
+                </defs>
+                <line
+                  // Add half of the icon width in order to center the lines
+                  x1={`${kilometersToCSSWidth(
+                    itemsByName[line.fromItem].x,
+                    SIZES.ICON_WIDTH_PERCENT / 2 - lineThickness
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/components/simulation-board.tsx]: wouldn't you want to divide lineThickness by two as well? so:
` (SIZES.ICON_WIDTH_PERCENT - lineThickness) / 2`

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx [hunk 3]
```diff
@@ -103,20 +105,21 @@ export const InputPage = () => {
...
+          <label>Simulation Date Slider</label>
+          <ReactSlider
+            className="horizontal-slider"
+            onChange={(val) => {
+              const daysFromStart = (val as unknown) as number;
+              const newDate = new Date();
+              newDate.setDate(EARLIEST_DATE.getDate() + daysFromStart);
+              setStartDate(newDate);
+            }}
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: can you change the end date or only the start date?

**Review by vitashubin — CHANGES_REQUESTED** [review]
Please wait on merging this until we can check out the demo :) thanks!

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx [hunk 4]
```diff
@@ -8,13 +8,69 @@ import SimulationBoard, {
...
+const SimBoardPlayable = (props: {
+  simulationResults: BiogridSimulationResults;
+  stateFrame: number;
+}) => {
+  const stateToGridItemRet = (state: any): GridItemRet[] => {
+    return state.nodes.map((node: any) => {
+      return {
+        gridItemName: node.value.gridItemName,
+        relativePosition: node.value.position ||
+          node.value.relativePosition || { x: 0, y: 0 },
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:31]: in what situation would it be beneficial for this to be the relativeposition?

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx [hunk 5]
```diff
@@ -39,35 +95,31 @@ export const SimulatePage = () => {
...
+    let finished = false;
+    let pause = () => {
+      finished = true;
+    };
+    const runThroughSteps = async () => {
+      for (let i = stateFrame; i < simResultsStateLen; i++) {
+        if (finished) {
+          return;
+        }
+        await new Promise((res, rej) =>
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:156]: why does this need to be wrapped in a promise?

File: biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts [hunk 6]
```diff
@@ -86,7 +86,7 @@ export class BioBattery implements Battery {
     return validate(batteryValidator);
   }
 
-  getEnergyInJoules(): Energy {
+  getEnergyInKilowattHour(): Energy {
     return this.energyInJoules;
```
Comment (vitashubin) [inline biogrid/libs/biogrid-simulator/src/lib/biobattery/biobattery-class.ts]: this is from the previous PR - but please make sure the variable name and getter function name match

File: biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts [hunk 7]
```diff
@@ -71,12 +71,12 @@ export class SolarPanel extends EnergySource {
...
    */
-  async getEnergyInJoules(date?: Date): Promise<Power> {
-    return await this.getPowerAmount(this.date || date);
+  async getEnergyInKilowattHour(date?: Date): Promise<Power> {
+    return await this.getPowerAmount(date || this.date);
   }
 
-  async isEmpty() {
-    return (await this.getEnergyInJoules()) === 0;
+  async isEmpty(date: Date) {
```
Comment (vitashubin) [inline biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts]: nit: it seems a bit unfortunate that all these functions have to be marked as async because this.getPowerAmount calls await this.weatherLib.setup(); which is the only promise in this entire chain that needs to be called. Can we call this.weatherLib.setup in the constructor of this class instead, that way the rest of the nested functions don't have to be async?

File: biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts [hunk 8]
```diff
@@ -282,11 +291,102 @@ export class Biogrid implements Grid {
...
+      newPos = { x: pos.x + xOffset, y: pos.y + yOffset };
+      // Increment the angle by 90 degrees
+      angle = angle + 90;
+      if (angle === 360) {
+        radius += bioconstants.GRID_DISTANCES.INCREMENTS_KM;
+        // Reset the angle
+        angle = 0;
+      }
+    }
+    if (outOfBoundsCount > 3) {
```
Comment (vitashubin) [inline biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts]: I do think it's a bit confusing having outOfBoundsCount being compared to 4 above and to 3 here. Can we make this consistent with `>3` and `<=3` above or the other way with 4?

**Review by vitashubin — CHANGES_REQUESTED** [review]

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx (hunk 3 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Oh it is just simulating one day now

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx (hunk 4 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:31]: Oh it is all relative to the 0,0 point of the grid. This is how backend describes it

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx (hunk 5 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:156]: it needs a promise so that the setTimeout function can be awaited to be called. So, the promise only resolves after the second of waiting is up. Thus the state frames are stepped through every second

File: biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts (hunk 7 above)
Comment (Lev-Stambler) [reply biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts]: Ok sure, I can mark this for a future issue

File: biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts (hunk 8 above)
Comment (Lev-Stambler) [reply biogrid/libs/biogrid-simulator/src/lib/biogrid/biogrid-class.ts]: ok sure

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx (hunk 3 above)
Comment (vitashubin) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: If that's the case, why do we have `daysFromStart`? Should that be `hoursFromStart` instead?

Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Also, does this assume the start time as midnight, or can we have two options for users - a start and end time?
Fine with leaving as is in this PR, but maybe add a TODO for users to be able to select a start time as well?

File: biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts (hunk 7 above)
Comment (vitashubin) [reply biogrid/libs/biogrid-simulator/src/lib/bioenergy-source/solar-panel.ts]: sg :)

**Review by vitashubin — CHANGES_REQUESTED** [review]

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx [hunk 9]
```diff
@@ -139,37 +206,30 @@ export const SimulatePage = () => {
...
-              <button onClick={() => setCurrentStateFrame(0)}>Reset</button>
-            </div>
-            <div>
-              Time of day:{' '}
-              {currentStateFrame % 12 === 0 ? 12 : currentStateFrame % 12}:00{' '}
-              {currentStateFrame >= 12 ? 'PM' : 'AM'}
+              <button
+                onClick={() => {
+                  const pauseFn = play();
+                  setControlSimultation({ pauseFN: pauseFn });
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx]: If I click play on a simulation and let it run for a bit, then (without hitting anything else), I click play again, I end up having two simulations running at the same time. I would recommend one of two options:
(1) one button, two states: when a user clicks "play", the button changes to say "pause". If a user clicks on it now, the simulation will pause, and the button text will again read "play" 
(2) before a user clicks "play", the pause button is disabled. When a user clicks "play", the pause button becomes enabled, but the "play" button is disabled. "Play" only becomes enabled again when "pause" is clicked

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx [hunk 10]
```diff
@@ -139,37 +206,30 @@ export const SimulatePage = () => {
...
+                }}
+              >
+                Play
+              </button>
+              <button onClick={() => pauseSimulation()}>Pause</button>
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:227]: another thing I noticed, it seems like when I click "pause", it moves one more state, and then pauses. It should pause on the current state

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx [hunk 11]
```diff
@@ -139,37 +206,30 @@ export const SimulatePage = () => {
...
+            <SimBoardPlayable
+              simulationResults={simulationResults}
+              stateFrame={stateFrame}
             />
           </div>
         </div>
       )}
+      {!simulationResults && (
+        <div className="loading-container">
+          <PacmanLoader />
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:249]: love this  :)

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx [hunk 12]
```diff
@@ -94,88 +96,121 @@ export const InputPage = () => {
...
+          <span className="tooltiptext">
+            The date where we will start collecting sunlight data from
+          </span>
           <div className="inputBox">
-            <label>End Date</label>
-            <DatePicker
-              showPopperArrow={false}
-              selected={endDate}
-              onChange={(date: Date) => setEndDate(date)}
+            <label>Start Date Slider </label>
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: why are we letting users pick a date, when the simulation can only run over one day and runs by hour? Shouldn't users pick which users they want their simulation to run for?

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx [hunk 13]
```diff
@@ -94,88 +96,121 @@ export const InputPage = () => {
...
+            <ReactSlider
+              className="horizontal-slider"
+              onChange={(val) => {
+                const daysFromStart = (val as unknown) as number;
+                const newDate = new Date();
+                newDate.setDate(EARLIEST_DATE.getDate() + daysFromStart);
+                setStartDate(newDate);
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: the way this is rendering now - it looks like a text date and it's not clear at all that it should be dragged, or that dragging it will change the start date, https://screenshot.googleplex.com/9QVY1VAFqHH.png

**Review by vitashubin — CHANGES_REQUESTED** [review]

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx (hunk 3 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Oh thats days from last week, I.e. if it today is sunday, 1 means one day from last sunday, thus monday. Changed name to daysFromLastWeek and added comment

Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Oh it would be like start day and end day. Currently, the simulation runs the 24 hours of the date chosen #89

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx (hunk 13 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Added a background and a better looking slide

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx (hunk 9 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx]: Fixed! (I hope :))

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx (hunk 13 above)
Comment (RolandNaijuka) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Is it possible to add the horizontal line on sliders here?

**Review by RolandNaijuka — COMMENTED** [review]
If you could also refactor the positions of the grid items to be on all sides. It looks like most of them are always placed on the right side

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx [hunk 14]
```diff
@@ -94,88 +96,128 @@ export const InputPage = () => {
...
           <div className="inputBox">
-            <label>End Date</label>
-            <DatePicker
-              showPopperArrow={false}
-              selected={endDate}
-              onChange={(date: Date) => setEndDate(date)}
-            />
+            <label>Simulation Date Slider</label>
+            <div className="slider-wrapper">
+              <ReactSlider
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: is this component the same as this one? https://material-ui.com/components/slider/
Wondering why they look different
It's helpful to use components users are familiar with and they come with a lot of built in functionality / UI work already done for you

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx [hunk 15]
```diff
@@ -94,88 +96,128 @@ export const InputPage = () => {
...
+            The date where we will start collecting sunlight data from
+          </span>
           <div className="inputBox">
-            <label>End Date</label>
-            <DatePicker
-              showPopperArrow={false}
-              selected={endDate}
-              onChange={(date: Date) => setEndDate(date)}
-            />
+            <label>Simulation Date Slider</label>
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: would prefer to have this use an action verb, e.g. "Select a Simulation Date"

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx [hunk 16]
```diff
@@ -17,13 +17,70 @@ import SimulationBoard, {
...
+        // Find the GitHub issue: https://github.com/googleinterns/step141-2020/issues/64
+        items={stateToGridItemRet(
+          props.simulationResults.states[
+            props.stateFrame < props.simulationResults.states.length
+              ? props.stateFrame
+              : 0
+          ]
+        )}
+        lines={stateToGridItemLines(
+          props.simulationResults.states[
```
Comment (vitashubin) [inline biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:63]: all simulations start at midnight, and go 6-8 hours without any arrows because there's no sunlight yet. Because of that when you click "play" it's not immediately obvious the simulation is running. Can we add a todo or add in this PR a change that shows some text like "no sunlight" if there's no arrows displayed in the sim for that hour

**Review by vitashubin — CHANGES_REQUESTED** [review]

File: biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx (hunk 16 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/simulate-page/simulate-page.tsx:63]: Added the TODO https://github.com/googleinterns/step141-2020/issues/90

File: biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx (hunk 14 above)
Comment (Lev-Stambler) [reply biogrid/apps/biogrid-mvp/src/app/pages/input-page/input-page.tsx]: Changed to material UI

**Review by vitashubin — CHANGES_REQUESTED** [review]
A couple of things
(1) hovering over the date selection slider brings up both the slider info and the tooltip. Can we have the tooltip only show up on the "select date" text so we don't have two pop ups for one action?
(2) can we have the slider info show tick marks with labels so users have an idea of what options are available?

File: biogrid/apps/api/src/app/services/Biogrid.ts [hunk 17]
```diff
@@ -67,25 +67,32 @@ export async function simulateNewBiogrid(
...
     // Start at midnight, increment hours until NUMBER_OF_SIM_HOURS reached
     currentDate.setHours(i);
     biogrid.updateEnergyUsage(currentDate);
     const action = await biobrain.computeAction(initState, currentDate);
     biogrid.takeAction(action);
     statesJson.push(biogrid.getJsonGraphDetails());
+    efficiencies.push(biogrid.getEfficiency());
   }
+  const efficienciesAddedUp = efficiencies
+    .filter((efficiency) => efficiency)
```
Comment (vitashubin) [inline biogrid/apps/api/src/app/services/Biogrid.ts:88]: does this filter do anything? looks like you're just passing through the same element

**Review by vitashubin — APPROVED** [review]
This looks great, thanks so much Lev! Approved pending 1 comment

File: biogrid/apps/api/src/app/services/Biogrid.ts (hunk 17 above)
Comment (Lev-Stambler) [reply biogrid/apps/api/src/app/services/Biogrid.ts:88]: It filters for any NaN values. Added a comment
